[package]
name = "kinetic_pic_electrostatic_3d"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
csv = "1"
glam = "0.29"
rand = "0.8"
serde = {version = "1", features = ["derive"] }
vtkio = "0.6.3"

[features]
bounds-check = []
